trigger:
  branches:
    include:
      - master
  paths:
    include:
      - src/VirtualNovel.Frontend/**

pool:
  vmImage: ubuntu-latest

variables:
  imageRepository: virtualnovel-frontend
  dockerfilePath: src/VirtualNovel.Frontend/Dockerfile
  tag: $(Build.BuildId)

steps:
  - checkout: self

  - task: Docker@2
    displayName: Build and push frontend
    inputs:
      command: buildAndPush
      containerRegistry: virtualnovel-acr-connection
      repository: $(imageRepository)
      dockerfile: $(dockerfilePath)
      buildContext: $(Build.SourcesDirectory)
      tags: |
        $(tag)
        latest